env:
  - OS_TYPE=centos 
language: python
cache: pip
python:
  - "3.6"
before_install:
  - mv fake_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
notifications:
  email: change

